
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 16;
  public static final int MENOR = 11;
  public static final int ELSE = 24;
  public static final int LLLAVE = 19;
  public static final int CADENA = 18;
  public static final int INT = 27;
  public static final int OR = 15;
  public static final int RPAREN = 6;
  public static final int IGUAL = 13;
  public static final int WHILE = 23;
  public static final int DIVISION = 9;
  public static final int SUMA = 8;
  public static final int IF = 22;
  public static final int LPAREN = 5;
  public static final int ID = 30;
  public static final int CADENATEXTO = 32;
  public static final int ASIGNAR = 17;
  public static final int DISTINTO = 14;
  public static final int MAYOR = 12;
  public static final int EOF = 0;
  public static final int MAIN = 21;
  public static final int BREAK = 28;
  public static final int PUTW = 25;
  public static final int NUMERO = 29;
  public static final int error = 1;
  public static final int PUTS = 26;
  public static final int PTOCOMA = 4;
  public static final int PRODUCTO = 7;
  public static final int ENTERO = 31;
  public static final int PARENTIZQ = 2;
  public static final int RLLAVE = 20;
  public static final int PARENTDER = 3;
  public static final int RESTA = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARENTIZQ",
  "PARENTDER",
  "PTOCOMA",
  "LPAREN",
  "RPAREN",
  "PRODUCTO",
  "SUMA",
  "DIVISION",
  "RESTA",
  "MENOR",
  "MAYOR",
  "IGUAL",
  "DISTINTO",
  "OR",
  "AND",
  "ASIGNAR",
  "CADENA",
  "LLLAVE",
  "RLLAVE",
  "MAIN",
  "IF",
  "WHILE",
  "ELSE",
  "PUTW",
  "PUTS",
  "INT",
  "BREAK",
  "NUMERO",
  "ID",
  "ENTERO",
  "CADENATEXTO"
  };
}

